Repository analogdevicesinc/scopy, pull requests merged in 2025-03, with the labels that each got.

#1959 workflows/docs: Add step for test report generation
  .github/workflows/generate_doc.yml
  docs/test_report_generator.py
Labels: testing

#1960 Preferences open preferences.ini button fix
  core/src/scopypreferencespage.cpp
Labels: v2.0

#1967 Bug fix pattern generator
  plugins/m2k/src/old/logicanalyzer/logicgroupitem.cpp
  plugins/m2k/src/old/logicanalyzer/logicgroupitem.h
  plugins/m2k/src/old/patterngenerator/pattern_generator.cpp
Labels: m2k, v2.0

#1975 m2k: fix the display resample in scenarios with ratio = 0
  plugins/m2k/src/old/signal_generator.cpp
  plugins/m2k/src/old/signal_generator.hpp
Labels: v2.0

#1979 m2k: disable MATLAB file support in the siggen for this release.
  plugins/m2k/src/old/signal_generator.cpp
Labels: v2.0

#1980 m2k: stop polling to update the DIO UI when the connection is lost.
  plugins/m2k/src/old/digitalio.cpp
Labels: v2.0
